# common
model_name: autobot
num_modes: 6    # K: number of trajectories for each agent [B, K, T, 5]
hidden_size: 128
num_encoder_layers: 2
num_decoder_layers: 2
tx_hidden_size: 384
tx_num_heads: 16
dropout: 0.1
entropy_weight: 40.0 # Regularization coefficient: Enhance the centrality of each mode
kl_weight: 20.0 # Regularization coefficient: controls the proximity of prior and posterior distributions
use_FDEADE_aux_loss: True

# train
max_epochs: 100 #150 #40
learning_rate: 0.00075 # 0.00075 # 1e-3 for lanegcn
learning_rate_sched: [ 10, 20, 30, 40, 50 ]
optimizer: Adam #According to PyTorch naming
scheduler: multistep # plateau, multistep
ewc_lambda: 2000
train_batch_size: 128 #32 #128
eval_batch_size: 256 #32 #128
grad_clip_norm: 5 # Gradient clipping threshold to avoid Transformer exploding gradients

# data related
max_num_agents: 50 # Exceeding the limit will truncate or discard the tail agent
map_range: 100 # Map cropping range centered on the AV (ego vehicle) (meters)
max_num_roads: 256 # Limits on the number of map lines and points per lane
max_points_per_lane: 20 # will be overwritten if manually_split_lane is True
# lane split related params
manually_split_lane: False # if True, lanes will be split with the same number of points and length, else, lanes will be split with the same number of points but varying length
point_sampled_interval: 1 # only used when manually_split_lane is True, the interval of points sampled from the original lane
num_points_each_polyline: 20 # only used when manually_split_lane is True, the number of points in each polyline
vector_break_dist_thresh: 1.0 # only used when manually_split_lane is True, the distance threshold to break the vector to split the lane
# be used to prevent polylines from being too long on irregular roads.


